// ─── Complete World Countries & Top Traveled Destinations ───────────────────

export interface CountryInfo {
  name: string;
  code: string;
  flag: string;
  region: 'Middle East' | 'Asia' | 'Europe' | 'Americas' | 'Africa' | 'Oceania';
  popularAirport?: string;
  airportCode?: string;
  isMostTraveled?: boolean;
  highlight?: string;
  tag?: string;
  travelNote?: string;
}

// ─── Most Traveled Countries Featured on Prominent Tiles ─────────────────────
export const MOST_TRAVELED_COUNTRIES: CountryInfo[] = [
  {
    name: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    region: 'Middle East',
    popularAirport: 'Dubai Intl / Zayed Intl',
    airportCode: 'DXB / AUH',
    isMostTraveled: true,
    highlight: '#1 Top Hub',
    tag: 'Tourist & Residence Visas',
    travelNote: 'Direct flights from every major city. 30/60 days tourist visas with instant approvals.',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    flag: '🇸🇦',
    region: 'Middle East',
    popularAirport: 'Riyadh / Jeddah (Hajj & Umrah)',
    airportCode: 'RUH / JED',
    isMostTraveled: true,
    highlight: 'Umrah & Tourism',
    tag: 'Saudi eVisa & Flights',
    travelNote: 'Express Saudi tourist eVisas & sacred Umrah pilgrimage packages from UAE.',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
    region: 'Europe',
    popularAirport: 'London Heathrow / Gatwick',
    airportCode: 'LHR / LGW',
    isMostTraveled: true,
    highlight: '6+ Daily Flights',
    tag: 'Direct Flights & Holidays',
    travelNote: 'Daily non-stop flights via Emirates, British Airways & Virgin Atlantic with luggage included.',
  },
  {
    name: 'India (Delhi & Mumbai)',
    code: 'IN-DEL',
    flag: '🇮🇳',
    region: 'Asia',
    popularAirport: 'Delhi / Mumbai Metros',
    airportCode: 'DEL / BOM',
    isMostTraveled: true,
    highlight: 'Frequent Daily',
    tag: 'Hourly Non-Stop Flights',
    travelNote: 'Hourly departures to major Indian metros with 30kg–40kg baggage allowances.',
  },
  {
    name: 'India — Kochi (Kerala)',
    code: 'IN-COK',
    flag: '🇮🇳',
    region: 'Asia',
    popularAirport: 'Cochin International Airport',
    airportCode: 'DXB → COK',
    isMostTraveled: true,
    highlight: 'Direct Daily',
    tag: 'Kerala Non-Stop Hub',
    travelNote: 'Direct 4-hour daily flights on Air India Express, Emirates, IndiGo & SpiceJet with 30kg+ checked luggage.',
  },
  {
    name: 'India — Bengaluru',
    code: 'IN-BLR',
    flag: '🇮🇳',
    region: 'Asia',
    popularAirport: 'Kempegowda Intl Airport (Bangalore)',
    airportCode: 'DXB → BLR',
    isMostTraveled: true,
    highlight: 'Silicon Capital',
    tag: 'Multiple Daily Directs',
    travelNote: 'Direct express routes connecting Dubai and South India tech hub with top baggage options.',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    flag: '🇵🇰',
    region: 'Asia',
    popularAirport: 'Karachi / Lahore / Islamabad',
    airportCode: 'KHI / LHE / ISB',
    isMostTraveled: true,
    highlight: 'High Demand',
    tag: 'Daily Non-Stop',
    travelNote: 'Affordable non-stop flights across Emirates, Flydubai, Airblue & PIA.',
  },
  {
    name: 'Turkey',
    code: 'TR',
    flag: '🇹🇷',
    region: 'Europe',
    popularAirport: 'Istanbul Airport / Sabiha Gokcen',
    airportCode: 'IST / SAW',
    isMostTraveled: true,
    highlight: 'Top Holiday',
    tag: 'Sightseeing & Shopping',
    travelNote: 'Two continents in one trip. Turkish eVisa assistance and luxury holiday packages.',
  },
  {
    name: 'Thailand',
    code: 'TH',
    flag: '🇹🇭',
    region: 'Asia',
    popularAirport: 'Bangkok / Phuket',
    airportCode: 'BKK / HKT',
    isMostTraveled: true,
    highlight: 'Beach Getaways',
    tag: 'Visa on Arrival / Tour',
    travelNote: 'Popular year-round tropical holidays, street food tours, and luxury island resorts.',
  },
  {
    name: 'Maldives',
    code: 'MV',
    flag: '🇲🇻',
    region: 'Asia',
    popularAirport: 'Velana Intl (Male)',
    airportCode: 'MLE',
    isMostTraveled: true,
    highlight: 'Luxury Island',
    tag: 'Flights + Overwater Villas',
    travelNote: '4-hour direct flight from Dubai. 30 days free visa on arrival for all nationalities.',
  },
  {
    name: 'Egypt',
    code: 'EG',
    flag: '🇪🇬',
    region: 'Africa',
    popularAirport: 'Cairo Intl / Alexandria',
    airportCode: 'CAI / HBE',
    isMostTraveled: true,
    highlight: 'Historic Cairo',
    tag: 'Daily Flights & Pyramids',
    travelNote: 'Multiple daily direct flights via EgyptAir & Emirates with generous 46kg baggage allowance.',
  },
  {
    name: 'United States',
    code: 'US',
    flag: '🇺🇸',
    region: 'Americas',
    popularAirport: 'New York (JFK) / Los Angeles (LAX)',
    airportCode: 'JFK / LAX / ORD',
    isMostTraveled: true,
    highlight: 'Direct Flights',
    tag: 'US B1/B2 Guidance',
    travelNote: 'Non-stop flights across North America with Emirates, United, and American Airlines.',
  },
  {
    name: 'Philippines',
    code: 'PH',
    flag: '🇵🇭',
    region: 'Asia',
    popularAirport: 'Manila (Ninoy Aquino) / Cebu',
    airportCode: 'MNL / CEB',
    isMostTraveled: true,
    highlight: 'Daily Direct',
    tag: '2x23kg Checked Bags',
    travelNote: 'Direct non-stop flights with Philippine Airlines, Cebu Pacific & Emirates.',
  },
  {
    name: 'Oman',
    code: 'OM',
    flag: '🇴🇲',
    region: 'Middle East',
    popularAirport: 'Muscat Intl / Salalah',
    airportCode: 'MCT / SLL',
    isMostTraveled: true,
    highlight: 'Visa Change & Trips',
    tag: 'Flight & Bus Border Run',
    travelNote: 'Neighboring Gulf haven for road trips, Khareef Salalah festival, and visa status changes.',
  },
  {
    name: 'Georgia',
    code: 'GE',
    flag: '🇬🇪',
    region: 'Europe',
    popularAirport: 'Tbilisi / Batumi',
    airportCode: 'TBS / BUS',
    isMostTraveled: true,
    highlight: 'Visa-Free / Easy',
    tag: 'Scenic Mountain Tours',
    travelNote: 'Only 3.5 hours from Dubai. Visa-free or easy eVisa for UAE residents.',
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    flag: '🇦🇿',
    region: 'Europe',
    popularAirport: 'Baku (Heydar Aliyev)',
    airportCode: 'GYD',
    isMostTraveled: true,
    highlight: 'Baku Escapes',
    tag: 'Fast eVisa in 3 Hours',
    travelNote: 'Direct daily 3-hour flights from Dubai/Sharjah. Modern skyline and rich historical culture.',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    flag: '🇲🇾',
    region: 'Asia',
    popularAirport: 'Kuala Lumpur / Penang',
    airportCode: 'KUL / PEN',
    isMostTraveled: true,
    highlight: 'Family Holidays',
    tag: 'Shopping & Nature',
    travelNote: 'Vibrant cultural mix, theme parks, and budget-friendly luxury family hotels.',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    flag: '🇨🇭',
    region: 'Europe',
    popularAirport: 'Zurich / Geneva',
    airportCode: 'ZRH / GVA',
    isMostTraveled: true,
    highlight: 'Alpine Paradise',
    tag: 'Schengen Visa Support',
    travelNote: 'Breathtaking Swiss Alps, scenic train passes, and direct daily departures from UAE.',
  },
];

// ─── Comprehensive List of All Countries (195+ Countries) ───────────────────
export const ALL_COUNTRIES: CountryInfo[] = [
  // Middle East
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', region: 'Middle East', airportCode: 'DXB', isMostTraveled: true },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', region: 'Middle East', airportCode: 'JED', isMostTraveled: true },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', region: 'Middle East', airportCode: 'MCT', isMostTraveled: true },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', region: 'Middle East', airportCode: 'DOH' },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', region: 'Middle East', airportCode: 'KWI' },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', region: 'Middle East', airportCode: 'BAH' },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', region: 'Middle East', airportCode: 'AMM' },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', region: 'Middle East', airportCode: 'BEY' },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', region: 'Middle East', airportCode: 'BGW' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', region: 'Middle East', airportCode: 'IKA' },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', region: 'Middle East', airportCode: 'ADE' },
  { name: 'Syria', code: 'SY', flag: '🇸🇾', region: 'Middle East', airportCode: 'DAM' },

  // Asia
  { name: 'India (All Metros)', code: 'IN', flag: '🇮🇳', region: 'Asia', airportCode: 'DEL / BOM', isMostTraveled: true },
  { name: 'India — Kochi (Kerala)', code: 'IN-COK', flag: '🇮🇳', region: 'Asia', airportCode: 'COK', isMostTraveled: true },
  { name: 'India — Bengaluru', code: 'IN-BLR', flag: '🇮🇳', region: 'Asia', airportCode: 'BLR', isMostTraveled: true },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', region: 'Asia', airportCode: 'KHI', isMostTraveled: true },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', region: 'Asia', airportCode: 'MNL', isMostTraveled: true },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', region: 'Asia', airportCode: 'BKK', isMostTraveled: true },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', region: 'Asia', airportCode: 'MLE', isMostTraveled: true },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', region: 'Asia', airportCode: 'KUL', isMostTraveled: true },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', region: 'Asia', airportCode: 'SIN' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', region: 'Asia', airportCode: 'CGK' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', region: 'Asia', airportCode: 'CMB' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', region: 'Asia', airportCode: 'DAC' },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵', region: 'Asia', airportCode: 'KTM' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', region: 'Asia', airportCode: 'HND' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷', region: 'Asia', airportCode: 'ICN' },
  { name: 'China', code: 'CN', flag: '🇨🇳', region: 'Asia', airportCode: 'PEK' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳', region: 'Asia', airportCode: 'HAN' },
  { name: 'Hong Kong', code: 'HK', flag: '🇭🇰', region: 'Asia', airportCode: 'HKG' },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼', region: 'Asia', airportCode: 'TPE' },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭', region: 'Asia', airportCode: 'PNH' },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', region: 'Asia', airportCode: 'TAS' },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', region: 'Asia', airportCode: 'ALA' },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', region: 'Asia', airportCode: 'FRU' },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯', region: 'Asia', airportCode: 'DYU' },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲', region: 'Asia', airportCode: 'ASB' },
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', region: 'Asia', airportCode: 'KBL' },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳', region: 'Asia', airportCode: 'ULN' },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲', region: 'Asia', airportCode: 'RGN' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦', region: 'Asia', airportCode: 'VTE' },
  { name: 'Brunei', code: 'BN', flag: '🇧🇳', region: 'Asia', airportCode: 'BWN' },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹', region: 'Asia', airportCode: 'PBH' },

  // Europe
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', region: 'Europe', airportCode: 'LHR', isMostTraveled: true },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷', region: 'Europe', airportCode: 'IST', isMostTraveled: true },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪', region: 'Europe', airportCode: 'TBS', isMostTraveled: true },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', region: 'Europe', airportCode: 'GYD', isMostTraveled: true },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', region: 'Europe', airportCode: 'ZRH', isMostTraveled: true },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', region: 'Europe', airportCode: 'FRA' },
  { name: 'France', code: 'FR', flag: '🇫🇷', region: 'Europe', airportCode: 'CDG' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', region: 'Europe', airportCode: 'FCO' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', region: 'Europe', airportCode: 'MAD' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱', region: 'Europe', airportCode: 'AMS' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', region: 'Europe', airportCode: 'VIE' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', region: 'Europe', airportCode: 'BRU' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', region: 'Europe', airportCode: 'ARN' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', region: 'Europe', airportCode: 'OSL' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', region: 'Europe', airportCode: 'CPH' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', region: 'Europe', airportCode: 'HEL' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', region: 'Europe', airportCode: 'DUB' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', region: 'Europe', airportCode: 'LIS' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', region: 'Europe', airportCode: 'ATH' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', region: 'Europe', airportCode: 'WAW' },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿', region: 'Europe', airportCode: 'PRG' },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', region: 'Europe', airportCode: 'BUD' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', region: 'Europe', airportCode: 'OTP' },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', region: 'Europe', airportCode: 'SOF' },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', region: 'Europe', airportCode: 'ZAG' },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', region: 'Europe', airportCode: 'BEG' },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', region: 'Europe', airportCode: 'LCA' },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲', region: 'Europe', airportCode: 'EVN' },
  { name: 'Russia', code: 'RU', flag: '🇷🇺', region: 'Europe', airportCode: 'SVO' },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', region: 'Europe', airportCode: 'KEF' },
  { name: 'Malta', code: 'MT', flag: '🇲🇹', region: 'Europe', airportCode: 'MLA' },

  // Americas
  { name: 'United States', code: 'US', flag: '🇺🇸', region: 'Americas', airportCode: 'JFK', isMostTraveled: true },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', region: 'Americas', airportCode: 'YYZ' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', region: 'Americas', airportCode: 'GRU' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', region: 'Americas', airportCode: 'MEX' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', region: 'Americas', airportCode: 'EZE' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', region: 'Americas', airportCode: 'BOG' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', region: 'Americas', airportCode: 'SCL' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪', region: 'Americas', airportCode: 'LIM' },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨', region: 'Americas', airportCode: 'UIO' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', region: 'Americas', airportCode: 'PTY' },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', region: 'Americas', airportCode: 'SJO' },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲', region: 'Americas', airportCode: 'KIN' },

  // Africa
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', region: 'Africa', airportCode: 'CAI', isMostTraveled: true },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', region: 'Africa', airportCode: 'JNB' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', region: 'Africa', airportCode: 'NBO' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', region: 'Africa', airportCode: 'LOS' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', region: 'Africa', airportCode: 'CMN' },
  { name: 'Tanzania (Zanzibar)', code: 'TZ', flag: '🇹🇿', region: 'Africa', airportCode: 'ZNZ' },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', region: 'Africa', airportCode: 'ADD' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', region: 'Africa', airportCode: 'ACC' },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬', region: 'Africa', airportCode: 'EBB' },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', region: 'Africa', airportCode: 'KGL' },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺', region: 'Africa', airportCode: 'MRU' },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨', region: 'Africa', airportCode: 'SEZ' },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', region: 'Africa', airportCode: 'ALG' },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', region: 'Africa', airportCode: 'TUN' },
  { name: 'Sudan', code: 'SD', flag: '🇸🇩', region: 'Africa', airportCode: 'KRT' },

  // Oceania
  { name: 'Australia', code: 'AU', flag: '🇦🇺', region: 'Oceania', airportCode: 'SYD' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', region: 'Oceania', airportCode: 'AKL' },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯', region: 'Oceania', airportCode: 'NAN' },
];
